# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(968, 1008)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea_display = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_display.setGeometry(QtCore.QRect(130, 10, 821, 941))
        self.scrollArea_display.setWidgetResizable(True)
        self.scrollArea_display.setObjectName("scrollArea_display")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 819, 939))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_display.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_cart = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cart.setGeometry(QtCore.QRect(20, 220, 93, 61))
        self.pushButton_cart.setObjectName("pushButton_cart")
        self.pushButton_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(20, 170, 93, 51))
        self.pushButton_login.setObjectName("pushButton_login")
        self.label_user = QtWidgets.QLabel(self.centralwidget)
        self.label_user.setGeometry(QtCore.QRect(30, 20, 72, 31))
        self.label_user.setTextFormat(QtCore.Qt.AutoText)
        self.label_user.setObjectName("label_user")
        self.label_phone = QtWidgets.QLabel(self.centralwidget)
        self.label_phone.setGeometry(QtCore.QRect(30, 70, 72, 31))
        self.label_phone.setObjectName("label_phone")
        self.label_address = QtWidgets.QLabel(self.centralwidget)
        self.label_address.setGeometry(QtCore.QRect(30, 120, 72, 31))
        self.label_address.setObjectName("label_address")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 968, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_cart.setText(_translate("MainWindow", "购物车/订单"))
        self.pushButton_login.setText(_translate("MainWindow", "用户"))
        self.label_user.setText(_translate("MainWindow", "用户"))
        self.label_phone.setText(_translate("MainWindow", "联系方式"))
        self.label_address.setText(_translate("MainWindow", "地址"))
