# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_login_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(464, 314)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 80, 321, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_user_name = QtWidgets.QLabel(self.layoutWidget)
        self.label_user_name.setObjectName("label_user_name")
        self.gridLayout.addWidget(self.label_user_name, 0, 0, 1, 1)
        self.lineEdit_user_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_user_name.setObjectName("lineEdit_user_name")
        self.gridLayout.addWidget(self.lineEdit_user_name, 0, 1, 1, 1)
        self.label_password = QtWidgets.QLabel(self.layoutWidget)
        self.label_password.setObjectName("label_password")
        self.gridLayout.addWidget(self.label_password, 1, 0, 1, 1)
        self.lineEdit_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.gridLayout.addWidget(self.lineEdit_password, 1, 1, 1, 1)
        self.pushButton_register = QtWidgets.QPushButton(Form)
        self.pushButton_register.setGeometry(QtCore.QRect(70, 240, 101, 41))
        self.pushButton_register.setObjectName("pushButton_register")
        self.pushButton_login = QtWidgets.QPushButton(Form)
        self.pushButton_login.setGeometry(QtCore.QRect(290, 240, 101, 41))
        self.pushButton_login.setObjectName("pushButton_login")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_user_name.setText(_translate("Form", "用户名"))
        self.label_password.setText(_translate("Form", "密码"))
        self.pushButton_register.setText(_translate("Form", "注册"))
        self.pushButton_login.setText(_translate("Form", "登录"))
