# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11487\Desktop\code\se_project\orderManage_module\ui_file\checkOrder.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 91, 21))
        self.label.setObjectName("label")
        self.con_info = QtWidgets.QTableWidget(self.centralwidget)
        self.con_info.setGeometry(QtCore.QRect(10, 80, 721, 61))
        self.con_info.setObjectName("con_info")
        self.con_info.setColumnCount(3)
        self.con_info.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.con_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.con_info.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.con_info.setHorizontalHeaderItem(2, item)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 72, 15))
        self.label_2.setObjectName("label_2")
        self.methodBox = QtWidgets.QComboBox(self.centralwidget)
        self.methodBox.setGeometry(QtCore.QRect(100, 180, 181, 31))
        self.methodBox.setObjectName("methodBox")
        self.methodBox.addItem("")
        self.methodBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 10, 111, 31))
        self.label_3.setObjectName("label_3")
        self.cartBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cartBtn.setGeometry(QtCore.QRect(550, 310, 93, 28))
        self.cartBtn.setObjectName("cartBtn")
        self.listTable = QtWidgets.QTableWidget(self.centralwidget)
        self.listTable.setGeometry(QtCore.QRect(10, 270, 401, 221))
        self.listTable.setObjectName("listTable")
        self.listTable.setColumnCount(3)
        self.listTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.listTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.listTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.listTable.setHorizontalHeaderItem(2, item)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 240, 72, 15))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "收货人信息："))
        item = self.con_info.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "姓名"))
        item = self.con_info.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "联系方式"))
        item = self.con_info.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "地址信息"))
        self.label_2.setText(_translate("MainWindow", "取货方式："))
        self.methodBox.setItemText(0, _translate("MainWindow", "超市配送"))
        self.methodBox.setItemText(1, _translate("MainWindow", "自行取货"))
        self.label_3.setText(_translate("MainWindow", "请完善订单信息"))
        self.cartBtn.setText(_translate("MainWindow", "返回购物车"))
        item = self.listTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "商品名"))
        item = self.listTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "单价"))
        item = self.listTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "购买数量"))
        self.label_4.setText(_translate("MainWindow", "商品清单："))
