# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '订单.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(932, 441)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(300, 20, 321, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(40, 60, 801, 281))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 360, 81, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(220, 360, 101, 23))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(390, 360, 104, 41))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 370, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", "            您好！欢迎来到订单管理界面！"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "订单编号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "校园卡号"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "收货人姓名"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "收货人电话"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "收货人地址"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "订单状态"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "配送方式"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "商品字典"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "消费总金额"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Form", "处理订单按钮"))
        self.pushButton_3.setText(_translate("Form", "刷新订单界面"))
        self.pushButton.setText(_translate("Form", "查看商品数据库"))
        self.textEdit.setPlaceholderText(_translate("Form", "请输入要处理的订单编号"))
        self.pushButton_2.setText(_translate("Form", "处理"))
