# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '订单.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1028, 545)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(340, 100, 321, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(80, 140, 881, 281))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 460, 131, 41))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", "            您好！欢迎来到订单管理界面！"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "订单编号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "校园卡号"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "收货人姓名"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "收货人电话"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "收货人地址"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "配送方式"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "订单状态"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "商品字典"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "消费总金额"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Form", "订单日期"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Form", "处理订单按钮"))
        self.pushButton_3.setText(_translate("Form", "刷新订单界面"))
