# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\l\Desktop\store_side\StoreManage\ui\buttonWidget\storeManage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(143, 333)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.insert_pushButton = QtWidgets.QPushButton(Form)
        self.insert_pushButton.setMinimumSize(QtCore.QSize(115, 28))
        self.insert_pushButton.setMaximumSize(QtCore.QSize(115, 28))
        self.insert_pushButton.setObjectName("insert_pushButton")
        self.verticalLayout.addWidget(self.insert_pushButton)
        self.updata_pushButton = QtWidgets.QPushButton(Form)
        self.updata_pushButton.setMinimumSize(QtCore.QSize(115, 28))
        self.updata_pushButton.setMaximumSize(QtCore.QSize(115, 28))
        self.updata_pushButton.setObjectName("updata_pushButton")
        self.verticalLayout.addWidget(self.updata_pushButton)
        self.delete_pushButton = QtWidgets.QPushButton(Form)
        self.delete_pushButton.setMinimumSize(QtCore.QSize(115, 28))
        self.delete_pushButton.setMaximumSize(QtCore.QSize(115, 28))
        self.delete_pushButton.setObjectName("delete_pushButton")
        self.verticalLayout.addWidget(self.delete_pushButton)
        self.tongji_pushButton = QtWidgets.QPushButton(Form)
        self.tongji_pushButton.setMinimumSize(QtCore.QSize(115, 28))
        self.tongji_pushButton.setMaximumSize(QtCore.QSize(115, 28))
        self.tongji_pushButton.setObjectName("tongji_pushButton")
        self.verticalLayout.addWidget(self.tongji_pushButton)
        self.pushButton_fresh = QtWidgets.QPushButton(Form)
        self.pushButton_fresh.setObjectName("pushButton_fresh")
        self.verticalLayout.addWidget(self.pushButton_fresh)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.insert_pushButton.setText(_translate("Form", "上架商品"))
        self.updata_pushButton.setText(_translate("Form", "修改商品信息"))
        self.delete_pushButton.setText(_translate("Form", "下架商品"))
        self.tongji_pushButton.setText(_translate("Form", "统计"))
        self.pushButton_fresh.setText(_translate("Form", "刷新"))
