# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\l\Desktop\软工大作业\se_project\StoreManage\ui\MerchWidget\merchWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(370, 264)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 40, 160, 107))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.picture = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.picture.setFrameShape(QtWidgets.QFrame.Box)
        self.picture.setObjectName("picture")
        self.horizontalLayout.addWidget(self.picture)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.namelable = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.namelable.setFrameShape(QtWidgets.QFrame.Box)
        self.namelable.setObjectName("namelable")
        self.verticalLayout.addWidget(self.namelable)
        self.pricelabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.pricelabel.setFrameShape(QtWidgets.QFrame.Box)
        self.pricelabel.setObjectName("pricelabel")
        self.verticalLayout.addWidget(self.pricelabel)
        self.numberlabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.numberlabel.setFrameShape(QtWidgets.QFrame.Box)
        self.numberlabel.setObjectName("numberlabel")
        self.verticalLayout.addWidget(self.numberlabel)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.picture.setText(_translate("Form", "商品图片"))
        self.namelable.setText(_translate("Form", "商品名称"))
        self.pricelabel.setText(_translate("Form", "商品价格"))
        self.numberlabel.setText(_translate("Form", "商品库存"))
        self.label_5.setText(_translate("Form", "商品类别"))
