# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\l\Desktop\软工大作业\se_project\StoreManage\ui\MerchWidget\merchWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(413, 130)
        self.picture = QtWidgets.QLabel(Form)
        self.picture.setGeometry(QtCore.QRect(5, 10, 91, 111))
        self.picture.setFrameShape(QtWidgets.QFrame.Box)
        self.picture.setObjectName("picture")
        self.namelable = QtWidgets.QLabel(Form)
        self.namelable.setGeometry(QtCore.QRect(100, 10, 156, 21))
        self.namelable.setFrameShape(QtWidgets.QFrame.Box)
        self.namelable.setObjectName("namelable")
        self.pricelabel = QtWidgets.QLabel(Form)
        self.pricelabel.setGeometry(QtCore.QRect(100, 70, 156, 21))
        self.pricelabel.setFrameShape(QtWidgets.QFrame.Box)
        self.pricelabel.setObjectName("pricelabel")
        self.numberlabel = QtWidgets.QLabel(Form)
        self.numberlabel.setGeometry(QtCore.QRect(100, 40, 156, 21))
        self.numberlabel.setFrameShape(QtWidgets.QFrame.Box)
        self.numberlabel.setObjectName("numberlabel")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(100, 100, 156, 21))
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setObjectName("label_5")
        self.pushButtonUpdate = QtWidgets.QPushButton(Form)
        self.pushButtonUpdate.setGeometry(QtCore.QRect(290, 30, 101, 28))
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.pushButtonDelete = QtWidgets.QPushButton(Form)
        self.pushButtonDelete.setGeometry(QtCore.QRect(290, 80, 101, 28))
        self.pushButtonDelete.setObjectName("pushButtonDelete")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.picture.setText(_translate("Form", "商品图片"))
        self.namelable.setText(_translate("Form", "商品名称"))
        self.pricelabel.setText(_translate("Form", "商品价格"))
        self.numberlabel.setText(_translate("Form", "商品库存"))
        self.label_5.setText(_translate("Form", "商品类别"))
        self.pushButtonUpdate.setText(_translate("Form", "修改商品信息"))
        self.pushButtonDelete.setText(_translate("Form", "下架商品"))
