# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\l\Desktop\软工大作业\se_project\StoreManage\ui\buttonWidget\Ui_storeManage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(129, 156)
        self.insert_pushButton = QtWidgets.QPushButton(Form)
        self.insert_pushButton.setGeometry(QtCore.QRect(20, 20, 93, 28))
        self.insert_pushButton.setObjectName("insert_pushButton")
        self.updata_pushButton = QtWidgets.QPushButton(Form)
        self.updata_pushButton.setGeometry(QtCore.QRect(20, 70, 93, 28))
        self.updata_pushButton.setObjectName("updata_pushButton")
        self.delete_pushButton = QtWidgets.QPushButton(Form)
        self.delete_pushButton.setGeometry(QtCore.QRect(20, 120, 93, 28))
        self.delete_pushButton.setObjectName("delete_pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.insert_pushButton.setText(_translate("Form", "上架商品"))
        self.updata_pushButton.setText(_translate("Form", "修改商品信息"))
        self.delete_pushButton.setText(_translate("Form", "下架商品"))
