# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\l\Desktop\软工大作业\se_project\StoreManage\ui\updatePage\updatePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(584, 527)
        self.Piclabel = QtWidgets.QLabel(Form)
        self.Piclabel.setGeometry(QtCore.QRect(30, 30, 171, 271))
        self.Piclabel.setObjectName("Piclabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(230, 30, 81, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.nameEdit = QtWidgets.QLineEdit(Form)
        self.nameEdit.setGeometry(QtCore.QRect(340, 60, 158, 24))
        self.nameEdit.setObjectName("nameEdit")
        self.priceEdit = QtWidgets.QLineEdit(Form)
        self.priceEdit.setGeometry(QtCore.QRect(340, 150, 158, 24))
        self.priceEdit.setObjectName("priceEdit")
        self.catEdit = QtWidgets.QLineEdit(Form)
        self.catEdit.setGeometry(QtCore.QRect(340, 320, 158, 24))
        self.catEdit.setObjectName("catEdit")
        self.numberEdit = QtWidgets.QLineEdit(Form)
        self.numberEdit.setGeometry(QtCore.QRect(340, 230, 158, 24))
        self.numberEdit.setObjectName("numberEdit")
        self.OKpushButton = QtWidgets.QPushButton(Form)
        self.OKpushButton.setGeometry(QtCore.QRect(90, 440, 93, 28))
        self.OKpushButton.setObjectName("OKpushButton")
        self.CancelpushButton = QtWidgets.QPushButton(Form)
        self.CancelpushButton.setGeometry(QtCore.QRect(290, 440, 93, 28))
        self.CancelpushButton.setObjectName("CancelpushButton")
        self.ChangePicButton = QtWidgets.QPushButton(Form)
        self.ChangePicButton.setGeometry(QtCore.QRect(30, 340, 93, 28))
        self.ChangePicButton.setObjectName("ChangePicButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "商品详情"))
        self.Piclabel.setText(_translate("Form", "商品图片"))
        self.label_2.setText(_translate("Form", "商品名称"))
        self.label_3.setText(_translate("Form", "商品价格"))
        self.label_4.setText(_translate("Form", "商品数量"))
        self.label_5.setText(_translate("Form", "商品种类"))
        self.OKpushButton.setText(_translate("Form", "确定"))
        self.CancelpushButton.setText(_translate("Form", "取消"))
        self.ChangePicButton.setText(_translate("Form", "修改图片"))
